### ISSUE TITLE
A couple of bugs to squash

### ISSUE THREAD

**Issue by jfkit** [jt196/paprika-to-obsidian-markdown#1]
Thanks very much for putting together this script. I've wanted my (over 800) Paprika recipes in my Obsidian vault, but didn't relish copying and pasting them all, and typing out the YAML for each one. I'm not quite ready to move everything into the vault, but hoping to soon.

I did come across a couple of bugs and wanted to let you know.

Bug 1: The script stops (at least for me) when it encounters a recipe which doesn't have a photo with it. My son was able to fix this, so let me know if you would like me to send the changes he made.

Bug 2: The script stopped when it encountered certain characters in either the recipe title, ingredients list, directions or notes. The main one in my recipes was this symbol:  ”  . It is called a Right Double Quotation Mark and differs slightly from the normal double quotation mark that's generated when you hit Shift and the button to the left of Enter on the (Windows) keyboard. My son wasn't able to find how to fix this bug, so I went through and manually replaced ” with ".  There were quite a few. 
There were only a few other characters that caused problems, such as a couple of cases where there was a slash (/) in the recipe title. Obviously that wasn't going to work when creating a filename, so needed to be removed.

I hope this helps and thanks again.

**Comment by jt196** [comment]
Thanks for the feedback. Likely this might just need some try except clauses in the code. You have any error codes for the "s?

**Comment by jfkit** [comment]
No, sorry.

**Comment by jt196** [comment]
Fixed in commit [5013504](https://github.com/jt196/paprika-to-obsidian-markdown/commit/50135041dc42c489c8b7de147c6422c3a4747e0d)
