### ISSUE TITLE
Special characters in titles produce error

### ISSUE THREAD

**Issue by a2jc4life** [jt196/paprika-to-obsidian-markdown#4]
Recipes containing asterisks, pipes, question marks, or colons throw up an error that interrupts the whole script. It makes complete sense for the script to be unable to process these (I realize they may conflict with coding, etc.) but it might be helpful to add this to the documentation.

**Comment by jt196** [comment]
@a2jc4life, as a simple fix for your issue #3, I used the Paprika export filename instead of the recipe name. This seems to have fixed things - I can't get it to error out on MacOS with asterisks, pipes or question marks.
